### ISSUE TITLE
error: ibvs_pkg/Marker.h: and world models

### ISSUE THREAD

**Issue by wangqing-W** [hang0610/ibvs_nmpc_px4#1]
First of all, I would like to express my gratitude to the senior who open-sourced their work. I have a minor bug to report: when the msg files and the cpp files that depend on the generated header files are in the same package, the first compilation will report an error that the header file is missing. For example:
`Errors << ibvs_pkg:make /home/cwkj/ibvs_nmpc_px4_ws/logs/ibvs_pkg/build.make.000.log
In file included from /home/cwkj/ibvs_nmpc_px4_ws/src/ibvs_pkg/src/ibvs_aruco.cpp:1:
/home/cwkj/ibvs_nmpc_px4_ws/src/ibvs_pkg/include/ibvs_aruco.h:43:10: fatal error: ibvs_pkg/Marker.h: No such file or directory
   43 | #include <ibvs_pkg/Marker.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ibvs_aruco.dir/build.make:63: CMakeFiles/ibvs_aruco.dir/src/ibvs_aruco.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:207: CMakeFiles/ibvs_aruco.dir/all] Error 2
make: *** [Makefile:141: all] Error 2`
My solution was to add the following to the CMakeLists.txt file:
`add_dependencies(ibvs_circle
  ibvs_pkg_generate_messages_cpp
  ${catkin_EXPORTED_TARGETS}
)`
Additionally, could you please let me know where I can find the "circle world" and "aruco world"? I am very grateful for your help.

**Comment by hang0610** [comment]
Hi Wangqing,

Thank you for your interest to my undergraduate project. Nice catch. You can create a pull request for this minor bug.
The models you want can be found at https://github.com/hang0610/PX4-Autopilot.

**Comment by wangqing-W** [comment]
Thank you very much for your help.

I successfully ported part of acados_circle to my PX4-Autopilot 1.13 version and ran simulations.

<img width="1088" alt="2" src="https://github.com/user-attachments/assets/46621c9b-39a6-4801-8d6d-00795972e016">


<img width="1229" alt="1" src="https://github.com/user-attachments/assets/91e7b400-25bb-468f-bac8-20001e07cb75">


However, I found that in drone.py:

`# for circle  
 quadrotorController = QuadrotorController(2, 5)`

If Th and N are too large, the drone tends to fly off course and doesn't complete the task well. I reduced the values, and now it can successfully fly through three rings.

Lastly, thank you again for your sharing; it has been a great help to me.

**Comment by hang0610** [comment]
Sounds great! Glad it helps. If you find my repo helpful, please consider citing it in your research/project:
```bibtex
@misc{ibvsnmpcpx4,
  author = {Zhang, Yuanhang},
  title = {Perception-constrained Visual Servoing Based NMPC for Quadrotor Flight},
  year = {2023},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/hang0610/ibvs_nmpc_px4}},
}
```
Thanks!
